### ISSUE TITLE
background() appears to leak goroutines

### ISSUE THREAD

**Issue by thomasmitchell** [tweedproject/tweed#16]
https://github.com/tweedproject/tweed/blob/8929e3ded343689e19e5bcae91e2f1ec3f39e084/task.go#L45

https://github.com/tweedproject/tweed/blob/8929e3ded343689e19e5bcae91e2f1ec3f39e084/task.go#L50

The e.run() call doesn't appear to close these two channels, and so would these functions ever return?

**Comment by jhunt** [comment]
Most definitely.  Do you know of a way to query a running go app for its current goroutines and their sleep/sync points?
